### ISSUE TITLE
Window

### ISSUE THREAD

**Issue by marqroldan** [icpepsemapua/icpepwebsite#1]
![image](https://user-images.githubusercontent.com/11716376/110178108-f0545f00-7e40-11eb-9522-71ed84fc1ca0.png)
![image](https://user-images.githubusercontent.com/11716376/110178308-39a4ae80-7e41-11eb-8442-e2e950455a2d.png)

![image](https://user-images.githubusercontent.com/11716376/110178765-e1ba7780-7e41-11eb-999d-3a29aefab10e.png)
![image](https://user-images.githubusercontent.com/11716376/110179035-5d1c2900-7e42-11eb-8d7e-6295c79c99fa.png)

**Comment by Foncemere** [comment]
This is no longer part of the design.
