### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by marqroldan** [icpepsemapua/icpepwebsite#12]

**Comment by marqroldan** [comment]
@tdcforonda Yo can we have the palette listed here so I could add them as variables in the scss file?

**Comment by tdcforonda** [comment]
> @tdcforonda Yo can we have the palette listed here so I could add them as variables in the scss file?

Here you go:

Yellow: 
#F8E9A1
RGB(247,233,160)

Pink: 
#F76C6C
RGB(247, 109, 109)

Light Blue: 
#A8D0E6
RGB(168, 209, 231)

Blue: 
#374785
RGB(55,71,133)

Dark Blue: 
#24315E
RGB(36,49,94)
